# Generated by Django 5.1.6 on 2025-02-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_streamplatform_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamplatform',
            name='about',
            field=models.TextField(max_length=150),
        ),
    ]
