# Generated by Django 5.1.6 on 2025-02-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_streamplatform_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
