# Generated by Django 5.1.6 on 2025-02-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_watchlist_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='storyline',
            field=models.TextField(max_length=150),
        ),
    ]
