# Generated by Django 5.1.6 on 2025-02-21 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_watchlist_storyline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='createdAt',
            new_name='created',
        ),
    ]
